---
groups:
- name: pipeline
  jobs:
  - shipit
- name: image
  jobs:
  - build-task-image

jobs:
- name: shipit
  plan:
  - get: repo
  - task: build-release-notes
    file: repo/ci/tasks/build-release-notes.yml
  - task: build-zip
    file: repo/ci/tasks/build-zips.yml

  - put: repo-github-release
    params:
      name: release-notes/name
      body: release-notes/notes.md
      tag: repo/VERSION
      tag_prefix: v
      globs: [zips/*.zip]

- name: build-task-image
  public: true
  serial: true
  plan:
  - get: repo-docker-image
    trigger: true
  - put: docker-image
    params:
      build: repo-docker-image/ci/ci_image

resources:
- name: repo
  type: git
  source:
    uri: git@github.com:viteinfinite/swift-buildpack.git
    branch: {{branch}}
    private_key: {{github-key}}

- name: repo-docker-image
  type: git
  source:
    uri: git@github.com:viteinfinite/swift-buildpack.git
    branch: {{branch}}
    private_key: {{github-key}}
    paths: [ci/ci_image/*]
- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: cfcommunity/pipeline-task-swift-buildpack

- name: repo-github-release
  type: github-release
  source:
    user: {{github-org}}
    repository: {{github-repository}}
    access_token: {{github-access-token}}
